default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT_EXTERNAL'] || 5432 %>

development:
  <<: *default
  database: fitness_dev_fuse

test:
  <<: *default
  database: fitness_dev_fuse_test

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE'] || 'fitness_production_fuse' %>
  username: <%= ENV['PRODUCTION_POSTGRES_USER'] %>
  password: <%= ENV['PRODUCTION_POSTGRES_PASSWORD'] %>
  host: <%= ENV['PRODUCTION_POSTGRES_HOST'] %>
  port: <%= ENV['PRODUCTION_POSTGRES_PORT'] %>
